#!/bin/bash
doShowUsage () {
cat <<EOF
Usage:
 ${slf:-${0##*/}} [-s CSV_SOURCE_PATH] [-d XLS_DEST_PATH ] [-H PREDICT_HOURS ] [-D] [-x] [-n] latitude longitude date hour
EOF
 return 0
}

(( $# )) || { doShowUsage; exit 1; }

ncep_pth='/store/GRIB/cooked/GFS4/NCEP'
order_pred_hours=120
flReCreateMP2LBL=0
flDontSaveCSV=0
flDontUnpackCSV=0
while getopts 's: d: H: DxnU' k; do
 case $k in
  s) ncep_pth="$OPTARG" ;;
  d) dest_pth="$OPTARG" ;;
  H) order_pred_hours="$OPTARG" ;;
  D) set -x ;;
  x) flReCreateMP2LBL=1 ;;
  n) flDontSaveCSV=1 ;;
  U) flDontUnpackCSV=1 ;;
  \?) echo "Unknown key: $k" >&2; doShowUsage; exit 1 ;;
 esac
done
shift $((OPTIND-1))

lat="$1"
lon="$2"
bdate="$3"
{ [[ $4 =~ ^[0-9]+$ ]] && declare -i bhours=$4; } || { doShowUsage; exit 1; }

if (( flReCreateMP2LBL )); then
 declare  -A MP2LBL
 for mp in 'TCDC-entire_atmosphere_(considered_as_a_single_layer)' {PRES,GUST,APCP,CSNOW,CRAIN,CICEP,CFRZR}-surface; do
  MP2LBL["$mp"]="${mp%%-*}"
 done

 for mp in {{U,V}GRD,RH,TMP}-{50,70,85}0_mb; do
  MP2LBL["$mp"]=$(sed -r 's%([UV]|T|RH)((GRD|MP)?)-(([57]0|85)0)_mb%\1\4%' <<<"$mp")
 done

 MP2LBL+=(['TMAX-2_m_above_ground']='Tmax' ['TMIN-2_m_above_ground']='Tmin' ['TMP-2_m_above_ground']='T')
 MP2LBL+=(['UGRD-10_m_above_ground']='U10m' ['VGRD-10_m_above_ground']='V10m' ['RH-2_m_above_ground']='RH2m')
else
 declare -A MP2LBL='(
		[UGRD-10_m_above_ground]="U10m"
		[UGRD-850_mb]="U850"
		[CSNOW-surface]="CSNOW"
		[CFRZR-surface]="CFRZR"
		[CRAIN-surface]="CRAIN"
		[TMP-500_mb]="T500"
		[RH-2_m_above_ground]="RH2m"
		[TMAX-2_m_above_ground]="Tmax"
		[GUST-surface]="GUST"
		[RH-700_mb]="RH700"
		[PRES-surface]="PRES"
		[TMP-850_mb]="T850"
		["TCDC-entire_atmosphere_(considered_as_a_single_layer)"]="TCDC"
		[CICEP-surface]="CICEP"
		[VGRD-10_m_above_ground]="V10m"
		[TMP-700_mb]="T700"
		[RH-500_mb]="RH500"
		[APCP-surface]="APCP"
		[UGRD-500_mb]="U500"
		[TMIN-2_m_above_ground]="Tmin"
		[VGRD-500_mb]="V500"
		[TMP-2_m_above_ground]="T"
		[UGRD-700_mb]="U700"
		[VGRD-850_mb]="V850"
		[RH-850_mb]="RH850"
		[VGRD-700_mb]="V700"
 )'
fi

declare -A NotInRA=(
		['APCP-surface']=3
		['CFRZR-surface']=3
		['CICEP-surface']=3
		['CRAIN-surface']=3
		['CSNOW-surface']=3
		['TCDC-entire_atmosphere_(considered_as_a_single_layer)']=3
		['TMAX-2_m_above_ground']=3
		['TMIN-2_m_above_ground']=3
)                                                                

declare -a LBLOrder=(
		'PRES'
		'TCDC'
		'CSNOW'
		'CRAIN'
		'CICEP'
		'CFRZR'
		'APCP'
		'GUST'
		'V500'
		'V700'
		'V850'
		'V10m'
		'U500'
		'U700'
		'U850'
		'U10m'
		'RH500'
		'RH700'
		'RH850'
		'RH2m'
		'T500'
		'T700'
		'T850'
		'Tmax'
		'Tmin'
		'T'
)

declare  -A LBL2MP

for mp in ${!MP2LBL[@]}; do
 LBL2MP[${MP2LBL["$mp"]}]="$mp"
done

bdate=${bdate//-/}
if ! [[ $bdate =~ ^(20[0-9]{2})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[01])$ ]]; then 
 if [[ $bdate =~ ^(0[1-9]|[1-2][0-9]|3[01])(0[1-9]|1[0-2])(20[0-9]{2})$ ]]; then
  bdate="${BASH_REMATCH[3]}${BASH_REMATCH[2]}${BASH_REMATCH[1]}"
 else
  echo 'Wrong date format!'; exit 1
 fi
fi

bhours=(bhours/6)*6
zz_bhours=$(printf '%02g' $bhours)

lola="${lon}00000,[[:space:]]*${lat}00000"

src_pth="${ncep_pth}/${bdate}"
if [[ ! -d $src_pth ]]; then
 src_pth="${ncep_pth}/${bdate:0:4}-${bdate:4:2}-${bdate:6:2}"
 [[ -d $src_pth ]] || exit 112
fi

cd "${dest_pth-.}"

csvFC="${bdate}_${zz_bhours}00_${lat//./}-${lon//./}.csv"

exec 3<&1 1>"$csvFC"

header="time,$(eval echo {0..${order_pred_hours}..3})"
echo "${header// /,}"

for lbl in ${LBLOrder[@]}; do
 echo -n "$lbl"
 
 mp=${LBL2MP["$lbl"]} 
 max_pred_hours=$(ls ${src_pth}/gfs_4_${bdate}_${zz_bhours}00_*_${mp}.csv*  | cut -d_ -f5 | sort -rn | head -1)
 if [[ $max_pred_hours =~ ^0*([0-9]+)$ ]]; then
  max_pred_hours=${BASH_REMATCH[1]}
 else
  eval "printf ',99999%.0s' {0..${order_pred_hours}..3}"
  continue
 fi
 pred_hours=$order_pred_hours
 (( max_pred_hours<order_pred_hours )) && pred_hours=$max_pred_hours
 start_pred_hour=0
 if [[ ${NotInRA["$mp"]} ]]; then
  start_pred_hour=3
  echo -n ',99999'
 fi  
 for si in $(seq -f '%03g' ${start_pred_hour} 3 ${pred_hours}); do
  csvSource="${src_pth}/gfs_4_${bdate}_${zz_bhours}00_${si}_${mp}.csv"
  flSourceIsFile=1
  if ! [[ -f "$csvSource" ]]; then
   if [[ -f "${csvSource}.gz" ]]; then
    if (( flDontUnpackCSV )); then    
     csvSource="(zcat \"${csvSource}.gz\")"
     flSourceIsFile=0
    else 
     gzip -d "${csvSource}.gz" &>/dev/null
    fi
   fi
  fi
  if (( flSourceIsFile )); then
   if ! [[ -f "$csvSource" ]]; then
    echo -n ',99999'
    continue
   fi
   csvSource=${csvSource//\(/\\(}
   csvSource=${csvSource//\)/\\)}
  fi
  echo -n $(eval "grep '$lola' <$csvSource" | awk -F', ?' '{print "," $3}' | tr -d '\n')
 done 
 (( max_pred_hours<order_pred_hours )) && \
  eval "printf ',99999%.0s' {$((pred_hours+3))..${order_pred_hours}..3}"
 echo
done
exec 1<&3

xlsFC=${csvFC/.csv/.xls}
csv2xls $xlsFC $csvFC
(( flDontSaveCSV )) || unix2dos -n $csvFC ${csvFC%.csv}_win.csv
rm -f $csvFC
